### ISSUE TITLE
Algoritmo de Dijkstra

### ISSUE THREAD

**Issue by VictorrOliver** [liviantorres/RotAgil#2]

**Comment by JeovaJrAguiar** [comment]
[28/07/2024] - 
- O algoritmo foi implementado dentro da tarefa que define o PathService

**Comment by JeovaJrAguiar** [comment]
[28/07/2024] - Domingo

Devido ao fato de já ter sido implementado, essa ISSUE será fechada.
Link para a ISSUE que foi implementado o algoritmo: https://github.com/liviantorres/RotAgil/issues/24
