### ISSUE TITLE
CRUD trajetos

### ISSUE THREAD

**Issue by VictorrOliver** [liviantorres/RotAgil#4]

**Comment by JeovaJrAguiar** [comment]
[17/07/2024] - Quarta-Feira
- Iniciando tarefa, analisando fluxo e delimitando implementações nescessárias.

**Comment by JeovaJrAguiar** [comment]
[18/07/2024] - Quinta-Feita
- Trarefa realizada, commit realizado: https://github.com/liviantorres/RotAgil/compare/main...ISSUE-4
- Segue para aprovação: @lucs-sb
